### PR TITLE
Fix RawString issue with Asciidoc and Markdown template extensions

### LINKED ISSUE #146: Allow to print asciidoc data value as html
Parameters passed to the asciidoc section are simply ignored.

Passing a parameter like this `{#asciidoc page.data.foo/} ` will be effectless.

if  `page.data.foo` contains asciidoc `{page.data.foo.asciidocToHtml.raw}` can be used instead.

Maybe this issue can closed.

### PR DESCRIPTION
**Pull request by ia3andy**
This allows to do https://github.com/quarkiverse/quarkus-qute-web/issues/146 but without the need of using `.raw`.

Closes #146

### CODE REVIEW

**Review by jtama — APPROVED** [review]
LGTM

File: asciidoc/runtime/src/main/java/io/quarkiverse/qute/web/asciidoc/runtime/AsciidocSectionHelperFactory.java [hunk 1]
```diff
@@ -3,13 +3,7 @@
...
 import java.util.concurrent.CompletionStage;
 
-import io.quarkus.qute.CompletedStage;
-import io.quarkus.qute.EngineConfiguration;
-import io.quarkus.qute.ResultNode;
-import io.quarkus.qute.SectionHelper;
-import io.quarkus.qute.SectionHelperFactory;
-import io.quarkus.qute.SingleResultNode;
-import io.quarkus.qute.TemplateExtension;
+import io.quarkus.qute.*;
```
Comment (mkouba) [inline asciidoc/runtime/src/main/java/io/quarkiverse/qute/web/asciidoc/runtime/AsciidocSectionHelperFactory.java:6]: Pls don't use wildcards for imports.

File: asciidoc/runtime/src/main/java/io/quarkiverse/qute/web/asciidoc/runtime/AsciidocSectionHelperFactory.java [hunk 2]
```diff
@@ -29,8 +23,8 @@ public AsciidocSectionHelper initialize(SectionInitContext context) {
     }
 
     @TemplateExtension(matchNames = { "asciidocify", "asciidocToHtml" })
-    static String convertToAsciidoc(String text, String ignoredName) {
-        return CONVERTER.apply(text);
+    static RawString convertToAsciidoc(String text, String ignoredName) {
```
Comment (mkouba) [inline asciidoc/runtime/src/main/java/io/quarkiverse/qute/web/asciidoc/runtime/AsciidocSectionHelperFactory.java:26]: How does it fix the problem with section params in #146? 

IIUIC this merely changes the behavior of `{text.asciidocToHtml}` in a way that it corresponds to `{text.asciidocToHtml.raw}`. Which is probably ok, unless someone wants to escape the result of conversion... which probably does not make a lot of sense, right?

**Review by mkouba — CHANGES_REQUESTED** [review]

File: asciidoc/runtime/src/main/java/io/quarkiverse/qute/web/asciidoc/runtime/AsciidocSectionHelperFactory.java (hunk 2 above)
Comment (jtama) [reply asciidoc/runtime/src/main/java/io/quarkiverse/qute/web/asciidoc/runtime/AsciidocSectionHelperFactory.java:26]: What I was trying to achieve with an attribute was to prevent the the rendered content of beeing escaped. So if we have another to achieve the same it's fine. 
It may be still be of some use to be able to pass attributes to the section but this would be a good start.

File: asciidoc/runtime/src/main/java/io/quarkiverse/qute/web/asciidoc/runtime/AsciidocSectionHelperFactory.java (hunk 1 above)
Comment (ia3andy) [reply asciidoc/runtime/src/main/java/io/quarkiverse/qute/web/asciidoc/runtime/AsciidocSectionHelperFactory.java:6]: Will fix it tomoz

File: asciidoc/runtime/src/main/java/io/quarkiverse/qute/web/asciidoc/runtime/AsciidocSectionHelperFactory.java (hunk 2 above)
Comment (ia3andy) [reply asciidoc/runtime/src/main/java/io/quarkiverse/qute/web/asciidoc/runtime/AsciidocSectionHelperFactory.java:26]: > How does it fix the problem with section params in #146?
> 
> IIUIC this merely changes the behavior of `{text.asciidocToHtml}` in a way that it corresponds to `{text.asciidocToHtml.raw}`. Which is probably ok, unless someone wants to escape the result of conversion... which probably does not make a lot of sense, right?

Yes that's why we make it the default behaviour, it doesn't make sense to use it escaped..

Comment (mkouba) [reply asciidoc/runtime/src/main/java/io/quarkiverse/qute/web/asciidoc/runtime/AsciidocSectionHelperFactory.java:33]: > Which is probably ok, unless someone wants to escape the result of conversion... 

Actually, in that case a user can do something like `{text.asciidocToHtml.value}`.

**Review by mkouba — APPROVED** [review]
